// --------------------------------------------------------
// 🪄 AUTO-GENERATED BY ORIVUSJS
// --------------------------------------------------------
// Do not edit this file manually.
// It is automatically updated by the Orivus CLI.
// --------------------------------------------------------

import { router } from "./router";
import { userRouter } from "@/domain/user/user.router";

export const appRouter = router({
  user: userRouter,
});

export type AppRouter = typeof appRouter;
