// --------------------------------------------------------
// 🪄 AUTO-GENERATED BY ORIVUSJS
// --------------------------------------------------------
import { router } from "./router";

export const appRouter = router({

});

export type AppRouter = typeof appRouter;
