// --------------------------------------------------------
// 🪄 AUTO-GENERATED BY ORIVUSJS
// --------------------------------------------------------
// Do not edit this file manually.
// It is automatically updated by the Orivus CLI.
// --------------------------------------------------------

import { router } from "./router";


export const appRouter = router({

});

export type AppRouter = typeof appRouter;
