import { ParsedModuleSpec } from "../../core/spec-parser";

/**
 * Generates a List Page (screen) for a module
 * Following the pattern from src/domain/user/screens/list.page.tsx
 */
export function generateListScreen(spec: ParsedModuleSpec): string {
    const model = spec.models[0];
    const modelName = model.name;

    return `"use client";

import { ${modelName}List, Create${modelName}Form } from "../ui";

export default function ${modelName}ListPage() {
    return (
        <main className="min-h-screen p-8 bg-gray-50">
            <div className="max-w-4xl mx-auto space-y-8">
                <div className="text-center">
                    <h1 className="text-4xl font-bold text-gray-900">${modelName} Management</h1>
                    <p className="mt-2 text-lg text-gray-600">Auto-generated by OrivusJS</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div>
                        <Create${modelName}Form />
                    </div>
                    <div>
                        <${modelName}List />
                    </div>
                </div>
            </div>
        </main>
    );
}
`;
}
