import fs from "fs";
import path from "path";

const DOMAIN_DIR = path.join(process.cwd(), "src/domain");
const OUTPUT_FILE = path.join(process.cwd(), "src/server/trpc/index.ts");

function generateRouter() {
    if (!fs.existsSync(DOMAIN_DIR)) {
        console.log("No domain directory found.");
        return;
    }

    const domains = fs.readdirSync(DOMAIN_DIR).filter((file) => {
        return fs.statSync(path.join(DOMAIN_DIR, file)).isDirectory();
    });

    const imports: string[] = [];
    const modules: string[] = [];

    domains.forEach((domain) => {
        const routerFile = `${domain}.router.ts`;
        const routerPath = path.join(DOMAIN_DIR, domain, routerFile);

        if (fs.existsSync(routerPath)) {
            const importName = `${domain}Router`;
            imports.push(`import { ${importName} } from "@/domain/${domain}/${domain}.router";`);
            modules.push(`  ${domain}: ${importName},`);
        }
    });

    const content = `// --------------------------------------------------------
// 🪄 AUTO-GENERATED BY ORIVUSJS
// --------------------------------------------------------
// Do not edit this file manually.
// It is automatically updated by the Orivus CLI.
// --------------------------------------------------------

import { router } from "./router";
${imports.join("\n")}

export const appRouter = router({
${modules.join("\n")}
});

export type AppRouter = typeof appRouter;
`;

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`✨ OrivusJS: AppRouter generated with ${domains.length} domains.`);
}

generateRouter();
